language: objective-c
osx_image: xcode7.3

env:
  global:
    - PROJECT=LogKit.xcodeproj
    - SCHEME_OSX="LogKit OSX"
    - SCHEME_IOS="LogKit iOS"
    - SCHEME_TVOS="LogKit tvOS"
    - SCHEME_WATCHOS="LogKit watchOS"

  matrix:
    - DEST="arch=x86_64"                    SCHEME="$SCHEME_OSX"     ACTION="test"
    - DEST="OS=9.3,name=iPhone 6S"          SCHEME="$SCHEME_IOS"     ACTION="test"
    - DEST="OS=9.2,name=Apple TV 1080p"     SCHEME="$SCHEME_TVOS"    ACTION="test"
    - DEST="OS=2.2,name=Apple Watch - 42mm" SCHEME="$SCHEME_WATCHOS" ACTION="build"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -destination "$DEST" -scheme "$SCHEME" -configuration Debug ONLY_ACTIVE_ARCH=NO $ACTION | xcpretty
